language: python

sudo: false

matrix:
  include:
  - os: linux
    compiler: clang
    env: CLANG_VERSION=12.0 LIBCXX=On
      - CC=clang-12.0
      - CXX=clang++-12.0
    addons:
      apt:
        sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-12.0']
        packages: ['clang-12.0']

python:
  - "3.9"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install

script:
  make coverage
  
after_success:
  coveralls
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b81f9ec6e179a91aaca0
    on_success: change
    on_failure: always
    on_start: false
