language: python

sudo: false

matrix:
  include:
  - env: CXX=clang++-15.0 CC=clang-15.0
    addons:
      apt:
        packages:
          - clang-15.0
          - libc++-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
            - llvm-toolchain-precise-15.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'

python:
  - "3.9"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install

script:
  make coverage
  
after_success:
  coveralls
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b81f9ec6e179a91aaca0
    on_success: change
    on_failure: always
    on_start: false
