language: python

sudo: false

python:
  - "3.9"

install:
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install

script:
  make coverage
  
after_success:
  coveralls
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b81f9ec6e179a91aaca0
    on_success: change
    on_failure: always
    on_start: false
