language: python

sudo: enabled

python:
  - "3.9"

dist: trusty
compiler: clang
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            sourceline:
              - deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-15 main
            key_url:
              - https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-15

install:
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install
  - ragazc compile examples/hello_world.zz

script:
  make coverage
  
after_success:
  coveralls
