language: python

sudo: false

python:
  - "3.9"
  - clang

before_install:  
  - sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-15 main"
  - sudo apt-get update -qq
  - sudo apt-get install --allow-unauthenticated -qq clang++-15.0

install:
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install
  - export CC="clang-15.0"
  - export CXX="clang++-15.0"

script:
  make coverage
  
after_success:
  coveralls
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b81f9ec6e179a91aaca0
    on_success: change
    on_failure: always
    on_start: false
