language: python

sudo: enabled

python:
  - "3.9"

dist: focal
compiler: clang
env: CLANG_VERSION=15.0 CC=clang-15.0 CXX=clang++-15.0 LIBCXX=On
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            sourceline:
              - deb http://apt.llvm.org/focal/ llvm-toolchain-focal-15 main
            key_url:
              - https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-15

install:
  - clang --version
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install

script:
  make coverage
  
after_success:
  coveralls
