language: python

sudo: enabled

python:
  - "3.9"

dist: focal
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            sourceline:
              - deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main
            key_url:
              - https://apt.llvm.org/llvm-snapshot.gpg.key
          packages:
            - clang-10
        
install:
  - cd ${TRAVIS_BUILD_DIR}
  - python setup.py install

script:
  make coverage
  
after_success:
  coveralls
