version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: pip install coveralls
      - run: pip install -r requirements.txt
      - run: python test.py

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_and_test
