version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: 
          name: Installing dependencies
          command: |
            - pip install coveralls
            - run: pip install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run: 
          name: Runnning tests
          command: |
            - coverage run test.py
            - coveralls

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
